version: "3.7"
services:
  docker_mysql57:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  product-service:
    build: ./product-service
    restart: always
    container_name: product-service
    ports:
      - 8081:8081
    depends_on:
      - docker_mysql57
      - discovery-service
      - api-gateway
    links:
      - docker_mysql57:db
      - discovery-service:eurekaserver
    environment: # Pass environment variables to the service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9000/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/product_ms?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8081

  cart-service:
    build: ./cart-service
    restart: always
    container_name: cart-service
    ports:
      - 8082:8082
    depends_on:
      - docker_mysql57
      - discovery-service
      - api-gateway
    links:
      - docker_mysql57:db
      - discovery-service:eurekaserver
    environment: # Pass environment variables to the service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9000/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cart_ms?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8082

  discovery-service:
    build: ./discovery-service
    restart: always
    ports:
      - 9000:9000

  api-gateway:
    build: ./api-gateway
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - discovery-service
    links:
      - discovery-service:eurekaserver
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9000/eureka
