server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : product-service
#          uri: http://localhost:8081
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/*/products/**
        - id: cart-service
#          uri: http://localhost:8082
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/*/carts/**

eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
