server:
  port: 9000

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9000/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    renewal-percent-threshold: 0.85
