spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product_ms?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect

  application:
    name: product-service
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  cloud:
    discovery:
      enabled: true
server:
  port: 8081

eureka:
  instance:
    appname: ${spring.application.name}
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka
#    enabled: false
